# Generated by Django 5.1.4 on 2024-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRRTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('index_type', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
