# Generated by Django 5.1.4 on 2024-12-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrtable',
            name='index_type',
        ),
    ]
