# Generated by Django 5.1.4 on 2024-12-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_remove_irrtable_index_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
