# Generated by Django 5.1.4 on 2024-12-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_financial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrtable',
            name='initial_investment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
