# Generated by Django 5.1.4 on 2024-12-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_irrtable_initial_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrtable',
            old_name='initial_investment',
            new_name='initial',
        ),
    ]
