# Generated by Django 5.1.4 on 2025-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_rename_initial_investment_irrtable_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrtable',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='irrtable',
            name='index',
        ),
        migrations.AddField(
            model_name='irrtable',
            name='credits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
